version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  # Maintain dependencies for Terraform Modules
  - package-ecosystem: "terraform"
    directory: "/modules"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "terraform"

  # Maintain dependencies for Terraform Examples
  - package-ecosystem: "terraform"
    directory: "/examples/production-baseline"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "terraform"
